# Generated by Django 2.1.7 on 2019-03-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='test@test.test', max_length=64),
            preserve_default=False,
        ),
    ]
