# Generated by Django 2.1.7 on 2019-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20190314_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('ava', models.ImageField(upload_to='media/avatars/')),
            ],
        ),
    ]
