# Generated by Django 2.2 on 2019-04-29 07:49

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='ava',
            field=models.ImageField(upload_to=Account.models.getAvaName),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
