# Generated by Django 2.1.7 on 2019-03-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_archive', models.FileField(upload_to='dicom/')),
                ('voxel_file', models.FileField(upload_to='voxels/')),
                ('patient_id', models.CharField(max_length=64, null=True)),
                ('study_uid', models.CharField(max_length=64)),
                ('series_uid', models.CharField(max_length=64)),
                ('AccessionNumber', models.CharField(max_length=128)),
                ('AcquisitionDate', models.CharField(max_length=128)),
                ('AcquisitionDateTime', models.CharField(max_length=128)),
                ('AcquisitionTime', models.CharField(max_length=128)),
                ('BodyPartExamined', models.CharField(max_length=128)),
                ('ContentDate', models.CharField(max_length=128)),
                ('ContentTime', models.CharField(max_length=128)),
                ('ConvolutionKernel', models.CharField(max_length=128)),
                ('DerivationDescription', models.CharField(max_length=128)),
                ('DeviceSerialNumber', models.CharField(max_length=128)),
                ('ExposureModulationType', models.CharField(max_length=128)),
                ('FilterType', models.CharField(max_length=128)),
                ('InstitutionAddress', models.CharField(max_length=128)),
                ('InstitutionName', models.CharField(max_length=128)),
                ('InstitutionalDepartmentName', models.CharField(max_length=128)),
                ('IssuerOfPatientID', models.CharField(max_length=128)),
                ('Manufacturer', models.CharField(max_length=128)),
                ('ManufacturerModelName', models.CharField(max_length=128)),
                ('Modality', models.CharField(max_length=128)),
                ('PatientAge', models.CharField(max_length=128)),
                ('PatientBirthDate', models.CharField(max_length=128)),
                ('PatientID', models.CharField(max_length=128)),
                ('PatientPosition', models.CharField(max_length=128)),
                ('PatientSex', models.CharField(max_length=128)),
                ('PerformedProcedureStepID', models.CharField(max_length=128)),
                ('PerformedProcedureStepStartDate', models.CharField(max_length=128)),
                ('PerformedProcedureStepStartTime', models.CharField(max_length=128)),
                ('PhotometricInterpretation', models.CharField(max_length=128)),
                ('PositionReferenceIndicator', models.CharField(max_length=128)),
                ('ProtocolName', models.CharField(max_length=128)),
                ('RetrieveAETitle', models.CharField(max_length=128)),
                ('RotationDirection', models.CharField(max_length=128)),
                ('ScanOptions', models.CharField(max_length=128)),
                ('ScheduledProcedureStepEndDate', models.CharField(max_length=128)),
                ('ScheduledProcedureStepEndTime', models.CharField(max_length=128)),
                ('ScheduledProcedureStepStartDate', models.CharField(max_length=128)),
                ('ScheduledProcedureStepStartTime', models.CharField(max_length=128)),
                ('SeriesDate', models.CharField(max_length=128)),
                ('SeriesDescription', models.CharField(max_length=128)),
                ('SeriesTime', models.CharField(max_length=128)),
                ('SoftwareVersions', models.CharField(max_length=128)),
                ('SpecificCharacterSet', models.CharField(max_length=128)),
                ('StackID', models.CharField(max_length=128)),
                ('StationAETitle', models.CharField(max_length=128)),
                ('StationName', models.CharField(max_length=128)),
                ('StudyDate', models.CharField(max_length=128)),
                ('StudyID', models.CharField(max_length=128)),
                ('StudyStatusID', models.CharField(max_length=128)),
                ('StudyTime', models.CharField(max_length=128)),
                ('BitsAllocated', models.IntegerField(default=0)),
                ('BitsStored', models.IntegerField(default=0)),
                ('Columns', models.IntegerField(default=0)),
                ('HighBit', models.IntegerField(default=0)),
                ('InStackPositionNumber', models.IntegerField(default=0)),
                ('PixelRepresentation', models.IntegerField(default=0)),
                ('Rows', models.IntegerField(default=0)),
                ('SamplesPerPixel', models.IntegerField(default=0)),
                ('TemporalPositionIndex', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Image Series',
            },
        ),
    ]
