# Generated by Django 2.2 on 2019-05-12 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageseries',
            name='doctorComment',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageseries',
            name='doctorCommentDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
