# Generated by Django 2.2 on 2019-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0002_auto_20190512_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorComment', models.CharField(default='', max_length=256)),
                ('doctorCommentDate', models.DateTimeField(auto_now_add=True)),
                ('seriesID', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='AcquisitionDateTime',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='AcquisitionTime',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='BodyPartExamined',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ContentDate',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ContentTime',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ConvolutionKernel',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='DerivationDescription',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='DeviceSerialNumber',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ExposureModulationType',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='InstitutionAddress',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='InstitutionName',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='InstitutionalDepartmentName',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='IssuerOfPatientID',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ManufacturerModelName',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='Modality',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='PerformedProcedureStepID',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='PerformedProcedureStepStartDate',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='PerformedProcedureStepStartTime',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='PhotometricInterpretation',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='PositionReferenceIndicator',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ProtocolName',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='RetrieveAETitle',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='RotationDirection',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ScheduledProcedureStepEndDate',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ScheduledProcedureStepEndTime',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ScheduledProcedureStepStartDate',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='ScheduledProcedureStepStartTime',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='StationAETitle',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='doctorComment',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='doctorCommentDate',
        ),
    ]
