# Generated by Django 2.2 on 2019-05-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0003_auto_20190512_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageseries',
            name='BitsAllocated',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='BitsStored',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='Columns',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='HighBit',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='InStackPositionNumber',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='PixelRepresentation',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='Rows',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='SamplesPerPixel',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='SpecificCharacterSet',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='StackID',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='TemporalPositionIndex',
        ),
    ]
